Software-Engineering-Household-Reminder-App: com.example.qreminder.dateChecker Class Reference
com.example.qreminder.dateChecker Class Reference
Static Public Member Functions
static boolean compare (Task task)
static List< Task > whatToNotify (List< Task > tasks)
static Date currentDate ()
Static Public Attributes
static Calendar cal = Calendar.getInstance()
static int cDay
static int cMonth
static int cYear
Member Function Documentation
compare()
static boolean com.example.qreminder.dateChecker.compare (Task task) static
References com.example.qreminder.dateChecker.cal, com.example.qreminder.dateChecker.cDay, com.example.qreminder.dateChecker.cMonth, com.example.qreminder.dateChecker.cYear, com.example.qreminder.Task.getDateDue(), com.example.qreminder.Task.getDay(), com.example.qreminder.Task.getMonth(), and com.example.qreminder.Task.getYear().
Referenced by com.example.qreminder.dateChecker.whatToNotify().
currentDate()
static Date com.example.qreminder.dateChecker.currentDate () static
References com.example.qreminder.dateChecker.cal, com.example.qreminder.dateChecker.cDay, com.example.qreminder.dateChecker.cMonth, and com.example.qreminder.dateChecker.cYear.
Referenced by com.example.qreminder.Task.update().
whatToNotify()
static List< Task > com.example.qreminder.dateChecker.whatToNotify (List< Task > tasks) static
References com.example.qreminder.dateChecker.compare().
Referenced by com.example.qreminder.myTasks.updateListView().
Member Data Documentation
cal
Calendar com.example.qreminder.dateChecker.cal = Calendar.getInstance() static
Referenced by com.example.qreminder.dateChecker.compare(), and com.example.qreminder.dateChecker.currentDate().
cDay
int com.example.qreminder.dateChecker.cDay static
Referenced by com.example.qreminder.dateChecker.compare(), and com.example.qreminder.dateChecker.currentDate().
cMonth
int com.example.qreminder.dateChecker.cMonth static
Referenced by com.example.qreminder.dateChecker.compare(), and com.example.qreminder.dateChecker.currentDate().
cYear
int com.example.qreminder.dateChecker.cYear static
Referenced by com.example.qreminder.dateChecker.compare(), and com.example.qreminder.dateChecker.currentDate().
The documentation for this class was generated from the following file:
C:/Users/emunrom950/AndroidStudioProjects/Software-Engineering-Household-Reminder-App/Qreminder/app/src/main/java/com/example/qreminder/dateChecker.java