Software-Engineering-Household-Reminder-App: com.example.qreminder.Task Class Reference
com.example.qreminder.Task Class Reference
Public Member Functions
Task (@NonNull String taskName, Date dateLastCompleted, int taskFrequency, int activeLevel)
Task ()
void setActive (int active)
void setName (@NonNull String newName)
void setDay (int day)
void setMonth (int month)
void setYear (int year)
void setDateDue (Date newDateDue)
void setFrequency (int newFrequency)
String getName ()
int getDay ()
int getActive ()
int getMonth ()
int getYear ()
Date getDateDue ()
int getFrequency ()
String dateString ()
String lastCompleted ()
String toString ()
Date dateDueFromDateComplete (Date lastCompleted)
void update ()
Constructor & Destructor Documentation
Task() [1/2]
com.example.qreminder.Task.Task (@NonNull String taskName, Date dateLastCompleted, int taskFrequency, int activeLevel)
Task() [2/2]
com.example.qreminder.Task.Task ()
Member Function Documentation
dateDueFromDateComplete()
Date com.example.qreminder.Task.dateDueFromDateComplete (Date lastCompleted)
dateString()
String com.example.qreminder.Task.dateString ()
Referenced by com.example.qreminder.TaskViewHolder.bind().
getActive()
int com.example.qreminder.Task.getActive ()
getDateDue()
Date com.example.qreminder.Task.getDateDue ()
Referenced by com.example.qreminder.dateChecker.compare().
getDay()
int com.example.qreminder.Task.getDay ()
Referenced by com.example.qreminder.dateChecker.compare().
getFrequency()
int com.example.qreminder.Task.getFrequency ()
Referenced by com.example.qreminder.customTask.onViewCreated().
getMonth()
int com.example.qreminder.Task.getMonth ()
Referenced by com.example.qreminder.dateChecker.compare().
getName()
String com.example.qreminder.Task.getName ()
Referenced by com.example.qreminder.TaskViewHolder.bind(), com.example.qreminder.EditTasksFragment.buildPopUp(), com.example.qreminder.myTasks.buildPopUp(), and com.example.qreminder.TaskViewHolder.buildPopUp().
getYear()
int com.example.qreminder.Task.getYear ()
Referenced by com.example.qreminder.dateChecker.compare().
lastCompleted()
String com.example.qreminder.Task.lastCompleted ()
Referenced by com.example.qreminder.customTask.onViewCreated().
setActive()
void com.example.qreminder.Task.setActive (int active)
setDateDue()
void com.example.qreminder.Task.setDateDue (Date newDateDue)
setDay()
void com.example.qreminder.Task.setDay (int day)
setFrequency()
void com.example.qreminder.Task.setFrequency (int newFrequency)
setMonth()
void com.example.qreminder.Task.setMonth (int month)
setName()
void com.example.qreminder.Task.setName (@NonNull String newName)
setYear()
void com.example.qreminder.Task.setYear (int year)
toString()
String com.example.qreminder.Task.toString ()
update()
void com.example.qreminder.Task.update ()
References com.example.qreminder.dateChecker.currentDate().
The documentation for this class was generated from the following file:
C:/Users/emunrom950/AndroidStudioProjects/Software-Engineering-Household-Reminder-App/Qreminder/app/src/main/java/com/example/qreminder/Task.java