Software-Engineering-Household-Reminder-App: com.example.qreminder.TaskViewHolder Class Reference
com.example.qreminder.TaskViewHolder Class Reference
Public Member Functions
void bind (Task t, TaskViewModel tvm)
void buildPopUp (Task task, View view, TaskViewModel tvm)
Member Function Documentation
bind()
void com.example.qreminder.TaskViewHolder.bind (Task t, TaskViewModel tvm)
References com.example.qreminder.Task.dateString(), and com.example.qreminder.Task.getName().
Referenced by com.example.qreminder.TaskListAdapter.onBindViewHolder().
buildPopUp()
void com.example.qreminder.TaskViewHolder.buildPopUp (Task task, View view, TaskViewModel tvm)
References com.example.qreminder.Task.getName().
The documentation for this class was generated from the following file:
C:/Users/emunrom950/AndroidStudioProjects/Software-Engineering-Household-Reminder-App/Qreminder/app/src/main/java/com/example/qreminder/TaskViewHolder.java