Software-Engineering-Household-Reminder-App: com.example.qreminder.customTask Class Reference
com.example.qreminder.customTask Class Reference
Public Member Functions
customTask ()
void onCreate (Bundle savedInstanceState)
View onCreateView (LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState)
void onViewCreated (@NonNull View view, Bundle savedInstanceState)
void openDatePicker (View view)
Constructor & Destructor Documentation
customTask()
com.example.qreminder.customTask.customTask ()
Member Function Documentation
onCreate()
void com.example.qreminder.customTask.onCreate (Bundle savedInstanceState)
onCreateView()
View com.example.qreminder.customTask.onCreateView (LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState)
onViewCreated()
void com.example.qreminder.customTask.onViewCreated (@NonNull View view, Bundle savedInstanceState)
References com.example.qreminder.Task.getFrequency(), com.example.qreminder.TaskViewModel.getTask(), and com.example.qreminder.Task.lastCompleted().
openDatePicker()
void com.example.qreminder.customTask.openDatePicker (View view)
The documentation for this class was generated from the following file:
C:/Users/emunrom950/AndroidStudioProjects/Software-Engineering-Household-Reminder-App/Qreminder/app/src/main/java/com/example/qreminder/customTask.java